import type { RefObject } from "react"
import { ErrorAlert } from "../layout/AsyncState.tsx"
import { Button } from "../ui/Button.tsx"
import type { useCustomerRegistry } from "../../hooks/customer-registry-hooks.ts"
import { identifierLabel } from "../../lib/invoice-authoring-state.ts"
import { ROMANIAN_COUNTIES } from "../../lib/romanian-counties.ts"
import { romanianCuiPattern } from "../../lib/vat-defaults.ts"

export const CustomerEditorSection = ({ state, headingRef }: { readonly state: ReturnType<typeof useCustomerRegistry>; readonly headingRef: RefObject<HTMLHeadingElement | null> }) => {
  const editing = state.editing
  return <section className="card sticky-card"><h2 ref={headingRef} tabIndex={-1} aria-live="polite">{editing === undefined ? "Client nou" : "Editează clientul"}</h2><p>Termenul de plată este opțional; dacă lipsește, se folosește valoarea din setările firmei.</p>{state.save.error === null ? null : <ErrorAlert error={state.save.error} />}<form key={editing?.id ?? "new"} onSubmit={state.submit}>
    <fieldset className="segmented-fieldset"><legend>Tip persoană</legend><div className="segmented-control compact-segments"><label><input type="radio" name="partyType" value="company" checked={state.partyType === "company"} onChange={() => { state.setPartyType("company") }} /><span>PJ</span></label><label><input type="radio" name="partyType" value="individual" checked={state.partyType === "individual"} onChange={() => { state.setPartyType("individual") }} /><span>PF</span></label></div></fieldset>
    <label>{state.partyType === "company" ? "Denumire" : "Nume complet"}<input name="name" required defaultValue={editing?.name ?? ""} /></label>
    <label>{identifierLabel(state.partyType)} {state.partyType === "individual" ? <span className="optional">opțional</span> : null}<input name="fiscalIdentifier" defaultValue={editing?.fiscalIdentifier ?? ""} pattern={state.partyType === "company" ? romanianCuiPattern : "(?:[0-9]{13})?"} maxLength={13} title={state.partyType === "company" ? "CUI românesc numeric; prefixul RO introdus este eliminat" : "CNP valid din 13 cifre sau câmp gol"} inputMode={state.partyType === "individual" ? "numeric" : "text"} onInput={(event) => { state.normalizeFiscalIdentifier(event.currentTarget) }} aria-describedby="customer-identifier-hint" /></label>
    <p className="hint left" id="customer-identifier-hint">{state.partyType === "company" ? "CUI-ul este salvat numeric; prefixul RO introdus este eliminat fără a modifica regimul TVA." : "CNP-ul este opțional și nu va fi completat artificial."}</p>
    {state.partyType === "company" ? <label className="checkbox-label"><input name="vatRegistered" type="checkbox" defaultChecked={editing?.partyType === "company" && editing.vatRegistered} /> Cumpărător înregistrat în scopuri de TVA</label> : null}
    <div className="form-grid two"><label>Țară<select value="RO" disabled><option value="RO">România (RO)</option></select></label><label>Localitate<input name="city" required defaultValue={editing?.address.city ?? ""} /></label><label className="span-two">Stradă și număr<input name="street" required defaultValue={editing?.address.street ?? ""} /></label><label>Județ<select name="county" required value={state.county} onChange={(event) => { state.setCounty(event.currentTarget.value) }}><option value="" disabled>Alege județul</option>{ROMANIAN_COUNTIES.map((county) => <option key={county.code} value={county.code}>{county.name}</option>)}</select></label>{state.sectorRequired ? <label>Sector<select name="sector" required defaultValue={editing?.address.sector ?? ""}><option value="" disabled>Alege sectorul</option>{[1, 2, 3, 4, 5, 6].map((sector) => <option key={sector} value={sector}>Sector {sector}</option>)}</select></label> : null}<label>Cod poștal <span className="optional">opțional</span><input name="postalCode" defaultValue={editing?.address.postalCode ?? ""} /></label></div>
    <label>Termen de plată <span className="optional">opțional, în zile</span><input name="defaultPaymentTermDays" type="number" min="0" max="3650" step="1" inputMode="numeric" defaultValue={editing?.defaultPaymentTermDays ?? ""} placeholder="Implicit firmă" /></label>
    <div className="form-actions">{editing === undefined ? null : <Button variant="ghost" disabled={state.save.isPending} onClick={state.cancelEdit}>Renunță</Button>}<Button type="submit" disabled={state.save.isPending}>{state.save.isPending ? "Se salvează…" : editing === undefined ? "Adaugă client" : "Salvează modificările"}</Button></div>
  </form></section>
}
